[project]
name = "morse-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.0",
    "sounddevice>=0.5.3",
    "streamlit>=1.52.2",
]
